full_body:
  pub: False
  mode: "fast"
  freq: 0.05
base:
  pub: True
  freq: 0.142857143
  mode: "fast_linear"
  limits:
    linear:
      default: [-0.25, 0.25]
      fast: [-0.3, 0.3]
      slow: [-0.04, 0.04]
    angular:
      default:  [-1.57, 1.57]
      fast: [-1.89, 1.89]
      slow: [-0.252, 0.252]
lift:
  pub: False
  freq: 0.2
  mode: "default"
  limits:
    default: [-0.11, 0.11]  # deafult linear vel m/s
    fast: [-0.13, 0.13]  # fast linear vel m/s
    slow: [-0.05, 0.05]  # slow  linear vel m/s
arm:
  pub: False
  freq: 0.2
  mode: "fast"
  limits:
    default: [-0.14, 0.14]  # deafult linear vel m/s
    fast: [-0.15, 0.15]  # fast linear vel m/s
    slow: [-0.05, 0.05]  # slow  linear vel m/s
wrist_yaw:
  pub: False
  freq: 0.2
  mode: "default"
  limits:
    default: [-2.0, 2.0]  # deafult  vel rad/s
    fast: [-2.5, 2.5]  # fast vel rad/s
    slow: [-0.75, 0.75]  # slow vel rad/s
