# Default initial positions for stretch_description's ros2_control fake system

initial_positions:
  joint_arm_l0: 0
  joint_arm_l1: 0
  joint_arm_l2: 0
  joint_arm_l3: 0
  joint_gripper_finger_left: 0
  joint_gripper_finger_right: 0
  joint_head_pan: 0
  joint_head_tilt: 0
  joint_lift: 0.2
  joint_wrist_yaw: 0
  position: 0